### ISSUE TITLE
example redusing

### ISSUE THREAD

**Issue by IrinaSing** [HackYourFutureBelgium/behavior-strategy-implementation#22]
Hello! 

There is probably a bug in this example, because it does not pass any assertions.
https://github.com/HackYourFutureBelgium/behavior-strategy-implementation/blob/master/array-methods/02-higher-order-functions/examples/reduce.js

I could not find the main problem in function but one minor is here:
line 48
```JS
const multiplyNumbers = (product, nextNumber) => {
  return product * nextNumber;
};

const _3_expect = 24;
const _3_actual = reduce(numbersArray, castToNumber);
console.assert(_3_actual === _3_expect, 'Test 3: multiply numbers');
```
There should be multiplyNumbers instead of castToNumber

**Comment by colevandersWands** [comment]
Besides the name of the function you mentioned, I'd also over-simplified the `reduce` function so it didn't handle initial values correctly.  I'm pushing a fix - thanks for the tip @IrinaSing

**Comment by colevandersWands** [comment]
> This example is really complicated to read and understand by the way 🤯

reduce is not so easy to understand.  Is it the test cases or the `reduce` function that are complicated?  If it's the use-cases then that can be simplified

**Comment by IrinaSing** [comment]
The function seems complicated in this particular example: few variables, control flow, loop. For me it is difficult to follow even with JSTutor.

**Comment by colevandersWands** [comment]
Maybe if there were two examples?  One with the `initialValue` parameter and one without:

```js
// without initialValue
const reduce = (arr, callback) => {
  let accumulator = arr[0];
  for (let i = 1; i < arr.length; i++) {
    const currentValue = arr[i];
    accumulator = callback(accumulator, currentValue, i);
  }
  return accumulator;
};
```

```js
// with initialValue
const reduce = (arr, callback, initialValue) => {
  let accumulator;
  let firstIndex;

  if (initialValue === undefined) {
    accumulator = arr[0];
    firstIndex = 1;
  } else {
    accumulator = initialValue;
    firstIndex = 0;
  }

  for (let i = firstIndex; i < arr.length; i++) {
    const currentValue = arr[i];
    accumulator = callback(accumulator, currentValue, i);
  }

  return accumulator;
};
```

**Comment by IrinaSing** [comment]
That could be useful I think.
