### ISSUE TITLE
Same exercises

### ISSUE THREAD

**Issue by IrinaSing** [HackYourFutureBelgium/behavior-strategy-implementation#27]
Hello!

It seems that those two exercises from about-testing have the same content:

[arrays-and-objects.test.js](https://github.com/HackYourFutureBelgium/behavior-strategy-implementation/blob/master/about-testing/exercises/1-testing-javascript/arrays-and-objects.test.js)
[reference-types.test.js](https://github.com/HackYourFutureBelgium/behavior-strategy-implementation/blob/master/about-testing/exercises/1-testing-javascript/reference-types.test.js)

Probably it should not be like that.

**Comment by colevandersWands** [comment]
Sure enough.  do you want to send a PR removing `reference-types.test.js`?  If not I can take care of it

**Comment by IrinaSing** [comment]
You can delete it 👍
